"use client";

import { useState, useRef, useEffect } from "react";
import { Send, Bot, User, Info } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { useAuth } from "@/hooks/useAuth";
import { assistantApi } from "@/lib/api";
import { cn } from "@/lib/utils";
import { SimulatedBadge } from "@/components/ui/SimulatedBadge";

interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
  sources?: Array<{ type: string; label: string }>;
  grounded?: boolean;
  timestamp: Date;
}

const SUGGESTED_QUERIES = [
  "What should I do today to grow my business?",
  "Why did my revenue fall?",
  "Which customers are at risk?",
  "Show me products that may stock out",
  "How can I recover my pending payments?",
  "What is my repeat purchase rate?",
];

export default function AIAssistantPage() {
  const { user, loading: authLoading } = useAuth();
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "welcome",
      role: "assistant",
      content: "Namaste! 👋 I'm your GrowthPilot AI assistant. I can help you analyze sales, find inactive customers, check inventory risks, and recover overdue payments. All numbers I share come directly from your data — not generated by AI.\n\nWhat would you like to know today?",
      timestamp: new Date(),
    },
  ]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const sendMessage = async (text: string) => {
    if (!text.trim() || loading) return;
    const userMsg: Message = {
      id: Date.now().toString(),
      role: "user",
      content: text.trim(),
      timestamp: new Date(),
    };
    setMessages((m) => [...m, userMsg]);
    setInput("");
    setLoading(true);

    try {
      const res = await assistantApi.chat(text.trim());
      const data = res.data;
      const assistantMsg: Message = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        content: data.response,
        sources: data.sources,
        grounded: data.grounded,
        timestamp: new Date(),
      };
      setMessages((m) => [...m, assistantMsg]);
    } catch {
      setMessages((m) => [
        ...m,
        {
          id: (Date.now() + 1).toString(),
          role: "assistant",
          content: "Sorry, I couldn't connect to the server. Please check that the backend is running.",
          timestamp: new Date(),
        },
      ]);
    } finally {
      setLoading(false);
    }
  };

  if (authLoading) return null;

  return (
    <AppShell>
      <div className="flex flex-col h-[calc(100vh-80px)] max-w-3xl mx-auto px-4 lg:px-0 py-4">
        {/* Header */}
        <div className="flex items-center gap-3 px-1 mb-4">
          <div className="w-9 h-9 bg-brand-600 rounded-xl flex items-center justify-center flex-shrink-0">
            <Bot size={18} className="text-white" aria-hidden="true" />
          </div>
          <div>
            <h1 className="font-semibold text-base">AI Assistant</h1>
            <p className="text-xs text-muted-foreground">Numbers come from your data, not from AI</p>
          </div>
          <SimulatedBadge className="ml-auto" />
        </div>

        {/* Grounding notice */}
        <div className="flex items-start gap-2 bg-muted rounded-xl px-3 py-2 mb-3 text-xs text-muted-foreground">
          <Info size={12} className="mt-0.5 flex-shrink-0" aria-hidden="true" />
          All ₹ amounts, customer counts, and percentages are sourced from your transaction data.
          The assistant cannot invent or guess numbers.
        </div>

        {/* Messages */}
        <div className="flex-1 overflow-y-auto space-y-4 pr-1" role="log" aria-live="polite" aria-label="Conversation">
          {messages.map((msg) => (
            <div
              key={msg.id}
              className={cn(
                "flex gap-3",
                msg.role === "user" ? "flex-row-reverse" : "flex-row"
              )}
            >
              {/* Avatar */}
              <div
                className={cn(
                  "w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5",
                  msg.role === "assistant"
                    ? "bg-brand-600 text-white"
                    : "bg-muted text-muted-foreground"
                )}
                aria-hidden="true"
              >
                {msg.role === "assistant" ? <Bot size={14} /> : <User size={14} />}
              </div>

              {/* Bubble */}
              <div
                className={cn(
                  "max-w-[85%] rounded-2xl px-4 py-3 text-sm",
                  msg.role === "assistant"
                    ? "bg-card border border-border"
                    : "bg-brand-600 text-white"
                )}
              >
                <p className="whitespace-pre-wrap">{msg.content}</p>

                {/* Source chips */}
                {msg.sources && msg.sources.length > 0 && (
                  <div className="mt-2 flex flex-wrap gap-1">
                    {msg.sources.map((s, i) => (
                      <span
                        key={i}
                        className="text-xs bg-muted text-muted-foreground px-2 py-0.5 rounded-full"
                      >
                        Based on: {s.label}
                      </span>
                    ))}
                  </div>
                )}

                {/* Grounded indicator */}
                {msg.role === "assistant" && msg.grounded === false && (
                  <p className="text-xs text-warning mt-1">⚠ Numbers could not be fully verified</p>
                )}

                <p className={cn(
                  "text-xs mt-1",
                  msg.role === "assistant" ? "text-muted-foreground" : "text-white/70"
                )}>
                  {msg.timestamp.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" })}
                </p>
              </div>
            </div>
          ))}

          {/* Loading indicator */}
          {loading && (
            <div className="flex gap-3">
              <div className="w-8 h-8 rounded-full bg-brand-600 flex items-center justify-center flex-shrink-0" aria-hidden="true">
                <Bot size={14} className="text-white" />
              </div>
              <div className="bg-card border border-border rounded-2xl px-4 py-3" role="status" aria-label="AI is thinking">
                <div className="flex gap-1">
                  {[0, 1, 2].map((i) => (
                    <div
                      key={i}
                      className="w-1.5 h-1.5 bg-muted-foreground rounded-full animate-bounce"
                      style={{ animationDelay: `${i * 0.15}s` }}
                    />
                  ))}
                </div>
              </div>
            </div>
          )}

          <div ref={bottomRef} />
        </div>

        {/* Suggested queries */}
        {messages.length <= 1 && (
          <div className="py-2">
            <div className="flex flex-wrap gap-2">
              {SUGGESTED_QUERIES.map((q) => (
                <button
                  key={q}
                  onClick={() => sendMessage(q)}
                  className="text-xs bg-muted hover:bg-accent text-muted-foreground hover:text-foreground px-3 py-1.5 rounded-full transition-colors"
                >
                  {q}
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Input */}
        <form
          onSubmit={(e) => { e.preventDefault(); sendMessage(input); }}
          className="flex gap-2 pt-3 border-t border-border mt-2"
        >
          <input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Ask about your business..."
            className="flex-1 px-4 py-2.5 border border-border rounded-xl text-sm bg-background focus:outline-none focus:ring-2 focus:ring-brand-500"
            disabled={loading}
            maxLength={500}
            aria-label="Message input"
          />
          <button
            type="submit"
            disabled={loading || !input.trim()}
            className="bg-brand-600 hover:bg-brand-700 disabled:opacity-50 text-white px-4 py-2.5 rounded-xl transition-colors"
            aria-label="Send message"
          >
            <Send size={16} aria-hidden="true" />
          </button>
        </form>
      </div>
    </AppShell>
  );
}
