"use client";

import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { RefreshCw, TrendingUp } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { OpportunityCard } from "@/components/ui/OpportunityCard";
import { useAuth } from "@/hooks/useAuth";
import { opportunitiesApi, actionsApi } from "@/lib/api";
import { formatRupeesRaw } from "@/lib/utils";
import { useRouter, useSearchParams } from "next/navigation";
import toast from "react-hot-toast";

export default function GrowthPage() {
  const { user, loading: authLoading } = useAuth();
  const router = useRouter();
  const searchParams = useSearchParams();
  const highlightId = searchParams.get("opp");
  const [proposing, setProposing] = useState<string | null>(null);

  const {
    data: oppsData,
    isLoading,
    refetch,
    isRefetching,
  } = useQuery({
    queryKey: ["opportunities"],
    queryFn: () => opportunitiesApi.list().then((r) => r.data),
    enabled: !!user,
  });

  if (authLoading) return null;

  const opps = oppsData?.opportunities ?? [];
  const totalImpact = opps.reduce(
    (sum: number, o: { estimated_impact_base_rupees: number }) => sum + (o.estimated_impact_base_rupees ?? 0),
    0
  );

  const handleAction = async (opp: { id: string; opportunity_type: string; estimated_impact_base_paise: number; action_params?: string }) => {
    setProposing(opp.id);
    try {
      let params: Record<string, unknown> = {};
      if (opp.action_params) {
        try { params = JSON.parse(opp.action_params); } catch {}
      }
      const res = await actionsApi.propose({
        opportunity_id: opp.id,
        action_type: opp.opportunity_type === "INVENTORY_RISK" ? "create_restock_order"
          : opp.opportunity_type === "PAYMENT_RECOVERY" ? "send_payment_reminder"
          : "create_campaign",
        params,
        estimated_impact_paise: Math.round((opp.estimated_impact_base_rupees ?? 0) * 100),
      });

      if (res.data.status === "BLOCKED") {
        toast.error(res.data.block_reason ?? "Action blocked by policy");
      } else if (res.data.status === "AWAITING_APPROVAL") {
        toast.success("Action queued for your approval!");
        router.push(`/actions/${res.data.action_id}`);
      } else {
        toast.success("Action created successfully!");
        router.push(`/actions/${res.data.action_id}`);
      }
    } catch (err) {
      toast.error("Failed to create action. Please try again.");
    } finally {
      setProposing(null);
    }
  };

  return (
    <AppShell>
      <div className="px-4 lg:px-8 py-6 max-w-5xl mx-auto">
        {/* Header */}
        <div className="flex items-start justify-between mb-6">
          <div>
            <h1 className="flex items-center gap-2">
              <TrendingUp size={20} className="text-brand-600" aria-hidden="true" />
              Growth Opportunities
            </h1>
            <p className="text-sm text-muted-foreground mt-1">
              AI-identified opportunities ranked by estimated revenue impact
            </p>
          </div>
          <button
            onClick={() => refetch()}
            disabled={isRefetching}
            className="flex items-center gap-2 px-3 py-2 border border-border rounded-lg text-sm text-muted-foreground hover:bg-muted transition-colors"
            aria-label="Refresh opportunities"
          >
            <RefreshCw size={14} className={isRefetching ? "animate-spin" : ""} aria-hidden="true" />
            Refresh
          </button>
        </div>

        {/* Summary */}
        {opps.length > 0 && (
          <div className="bg-brand-50 dark:bg-brand-900/20 border border-brand-100 dark:border-brand-800 rounded-xl p-4 mb-6">
            <p className="text-sm font-medium text-brand-800 dark:text-brand-300">
              <span className="text-2xl font-bold">{opps.length}</span> opportunities found &nbsp;·&nbsp;
              Combined estimated impact:{" "}
              <span className="font-bold rupee">{formatRupeesRaw(totalImpact)}</span>
            </p>
            <p className="text-xs text-brand-600 dark:text-brand-400 mt-1">
              All estimates are computed from your transaction data — not generated by AI.
              Impact ranges reflect conservative (low) to optimistic (high) scenarios.
            </p>
          </div>
        )}

        {/* Opportunities list */}
        {isLoading ? (
          <div className="space-y-4">
            {[1, 2, 3].map((i) => (
              <div key={i} className="h-48 bg-muted rounded-xl animate-pulse" />
            ))}
          </div>
        ) : opps.length === 0 ? (
          <div className="bg-card border border-border rounded-xl p-12 text-center">
            <TrendingUp size={40} className="text-muted-foreground mx-auto mb-3" />
            <p className="font-medium">No opportunities found</p>
            <p className="text-sm text-muted-foreground mt-1">
              Run &quot;Grow my business&quot; from the Command Center to discover opportunities.
            </p>
          </div>
        ) : (
          <div className="space-y-4">
            {opps.map((opp: Parameters<typeof OpportunityCard>[0]["opportunity"]) => (
              <OpportunityCard
                key={opp.id}
                opportunity={opp}
                onAction={() => handleAction(opp as Parameters<typeof handleAction>[0])}
                className={highlightId === opp.id ? "ring-2 ring-brand-500" : ""}
              />
            ))}
          </div>
        )}

        <p className="text-xs text-muted-foreground text-center mt-8">
          Numbers sourced from transaction and inventory data · Sandbox · Synthetic Demo Data
        </p>
      </div>
    </AppShell>
  );
}
